### ISSUE TITLE
init website infrastructure

### ISSUE THREAD

**Issue by vilnacrm** [VilnaCRM-Org/infrastructure#1]
As a DevOps, I need to be able to develop infrastructure using GitHub and terraform.

### Tasks

- [x] create an AWS account for Terraform
- [x] configure an IAM policies
- [x] create and configure the Cloudflare account
- [x] create an AWS account
- [x] set up CI checks for infrastructure repository through GitHub Actions (**tflint**, **terrascan**, **checkov**, **tfsec**, **infracost**, **terraform-docs**, **inframap**, **terraform fmt**, **terraform validate**)

### Acceptance Criteria

- [x] CI checks works
- [x] AWS and Cloudflare accounts registered and prepared for DevOps work
