### ISSUE TITLE
set up the frontend production infrastructure

### ISSUE THREAD

**Issue by vilnacrm** [VilnaCRM-Org/infrastructure#2]
As a frontend user, I need to be able to merge pull requests to the main branch and see my features and fixes on the production vilnacrm.com.

### Tasks

- [ ] configure Terraform for frontend (Cloudflare, AWS S3)
- [ ] configure GitHub Actions to deploy production
- [ ] create health checks for deploying production
- [ ] configure logs, monitoring, and alerting for frontend through AWS CloudWatch (Maybe: ELK, Prometheus, Grafana)
- [ ] configure alerting channels in Slack (sentry, cloud watch, Prometheus, uptime robot)
- [ ] set up canary releases for the frontend production deployments
- [ ] set up feature toggles for the production deployments (use Sentry errors for tracking unhealthy releases)
- [ ] cover the code with auto-tests

### Acceptance Criteria

- [ ] new features deployed to the production after merging pull requests to the main branch
- [ ] health checks works
- [ ] all teams can see logs and monitoring information
- [ ] alerts works and writes to the slack
- [ ] production deploying according to the rules of the canary release
- [ ] feature toggles works for the frontend deployments
- [ ] all infrastructure tests passed
