### ISSUE TITLE
implement website infrastructure

### ISSUE THREAD

**Issue by vilnacrm** [VilnaCRM-Org/infrastructure#3]
As a developer, I need to be able to implement, test, and maintain the website in various environments (sandbox, production)

### Tasks

- [ ] init website infrastructure #1
- [ ] set up the frontend production infrastructure #2
- [ ] set up a frontend sandbox infrastructure

### Acceptance Criteria

- [ ] all tasks finished
